### ISSUE TITLE
Failed to load the configuration file

### ISSUE THREAD

**Issue by Suryanshuraghav007** [owasp-amass/amass#1007]
Hello Amass Team,

I am experiencing an issue with the latest version of Amass where the APIs I configured are not activating, despite following the standard procedures for configuration. I'm detailing the steps I've taken below to aid in troubleshooting:

Configuration File Source: Downloaded the default datasources.yaml from the official [Amass GitHub repository](https://github.com/owasp-amass/amass/blob/master/examples/datasources.yaml) to ensure there are no syntax errors.

File Placement: Placed the datasources.yaml file in the default Amass config directory at ~/.config/amass/datasources.yaml.

API Configuration: Configured all my APIs correctly within the datasources.yaml file.

Command Used: The specific command I am running is amass enum -list -config ~/.config/amass/config.yaml
Issue Faced: 
![Screenshot from 2024-01-03 00-50-58](https://github.com/owasp-amass/amass/assets/109915850/fcd82fa0-716d-43b7-84ac-b041ab7dc4d3)
Impact: This issue is particularly concerning as I have invested in multiple API services specifically for use with Amass, and the current inability to integrate these services effectively is causing significant inconveni
ence and financial impact.

Request for Assistance:
I would appreciate guidance on how to resolve this issue. If there are any additional steps I should take, alternative configurations, or if this is a known issue with a workaround, your assistance would be greatly appreciated.

Additional Information:

Amass Version: v4.2.0

**Comment by The-Inceptions** [comment]
Please check out the response I provided in issue #1000.
