### ISSUE TITLE
in the last versions of amass, how can I view the subdomains only ? like subfinder 

### ISSUE THREAD

**Issue by Raammi** [owasp-amass/amass#1010]
also why I feel like amass is not using the api's provided in the configuration file ?

**Comment by 0xpr4bin** [comment]
Yes very poor updates, its completely lost to subfinder, i am uninstalling amass

**Comment by localhost-MouhannadlrX** [comment]
Really weird update!

**Comment by MMquant** [comment]
`grep FQDN /.config/amass | cut -d' ' -f1 | sort -u`

**Comment by caffix** [comment]
There are tools that can do this for you:

https://github.com/owasp-amass/oam-tools
