### ISSUE TITLE
there is no config.yaml file in ~/.config/amass

### ISSUE THREAD

**Issue by qran253** [owasp-amass/amass#1017]
there is no config.yaml datasources.yaml file in ~/.config/amass

**Comment by mzpqnxow** [comment]
You can put them there

- https://github.com/owasp-amass/amass/blob/master/examples/datasources.yaml
- https://github.com/owasp-amass/amass/blob/master/examples/config.yaml

**Comment by mzpqnxow** [comment]
See also #992 ...

**Comment by caffix** [comment]
Thank you @mzpqnxow
