### ISSUE TITLE
unmarshal error

### ISSUE THREAD

**Issue by rext49612** [owasp-amass/amass#1018]
#1008 ERROR OUTPUT with ini format#
Failed to load the configuration file: error mapping configuration settings to internal values: yaml: unmarshal errors:
  line 32: cannot unmarshal !!seq into config.Config

#datasource.yaml ERROR
Unable to read the context after specifying with -config flag , tried in docker still unable to read the file even filetype too.

literally no way to specify config file 

#Need attention
Regards @rext49612

**Comment by prasgop** [comment]
https://github.com/owasp-amass/config#installing-oam_i2y- 
https://github.com/owasp-amass/amass/issues/991 

https://github.com/owasp-amass/config/blob/master/docs/oam_i2y_user_guide.md
oam_i2y -ini config.ini

**Comment by The-Inceptions** [comment]
@prasgop @rext49612 can you provide your configuration file? and what version of amass are you running?

**Comment by prasgop** [comment]
version 4.2.0. 
It was throwing error when I initially tried to use the example congif.yaml by uncommenting api sources fields after adding respective keys. I later used oam_i2y to create config and datasources.yaml (new files attached) from config.ini, and it worked. 
[config.txt](https://github.com/owasp-amass/amass/files/14812754/config.txt)
[datasources.txt](https://github.com/owasp-amass/amass/files/14812755/datasources.txt)

Now, I am able to run amass. Just that it's runtime is kind of unpredictable.  And, I am using oam_subs after running amass to get subdomains as a separate list.

**Comment by The-Inceptions** [comment]
@prasgop as I look into this, I would advise you to redact your API keys in this file.

**Comment by prasgop** [comment]
oh yes, I should have. I have removed it now as it's anyway not adding any additional info to the context here.

**Comment by The-Inceptions** [comment]
@rext49612 Would you be willing to provide a redacted version of your `datasources.yaml` and your `config.yaml`?
