### ISSUE TITLE
bugged output?

### ISSUE THREAD

**Issue by marcelo321** [owasp-amass/amass#1035]
I am running `amass enum -d -passive" command, and sometimes I get outut like:

```
sub
sub2
sub3
```

but sometimes the same command gives output like this:

```

events-test.asana.com (FQDN) --> a_record --> 18.67.65.7 (IPAddress)
events-test.asana.com (FQDN) --> a_record --> 18.67.65.58 (IPAddress)
events-test.asana.com (FQDN) --> a_record --> 18.67.65.60 (IPAddress)
```

any idea why? I just want to print subdomains only.

**Comment by mzpqnxow** [comment]
Is this occurring on the same system or two different systems?

Just a guess, you may have a user or global configuration file on one system that is specifying the more verbose format

I don't recall the config file search path, but you check for the directory ~/config/amass as a start

You could also try something like this to see what files are being opened to help find it:

    strace -e open -f /path/to/amass ... args 2>&1 | grep -Fv .so

**Comment by caffix** [comment]
Please use the Amass Docker Compose. All the tools are available in the compose environment
