### ISSUE TITLE
Big Bug

### ISSUE THREAD

**Issue by mamalirn123** [owasp-amass/amass#1039]
Hi
from 2 month ago the subdomain enumration of amass not working well and somehow corrupted look at these : 
![image](https://github.com/user-attachments/assets/7e046183-d090-4969-ac38-b87069755595)
![image](https://github.com/user-attachments/assets/7ce48b5a-e19a-44d8-b55e-4726aa4d81da)

i just need subdomains but there is lot of unwanted data ! it was run on oh my zsh 
thank you

**Comment by mamalirn123** [comment]
Hi
the problem solved with downgrade the amass version and the problem still not fixed ! 
just remove the amass and reinstall it with this command :) 
`go install -v github.com/owasp-amass/amass/v3/...@master`

**Comment by akshaygupta99** [comment]
Seems like I was facing similar issues
