### ISSUE TITLE
oam-tools missing

### ISSUE THREAD

**Issue by mariuskimmina** [owasp-amass/amass#1042]
https://github.com/owasp-amass/oam-tools doesn't exist anymore, it's returning a 404. 
I also couldn't find it under a different name - what happened here? 

http://web.archive.org/web/20240523093821/https://github.com/owasp-amass/oam-tools

**Comment by caffix** [comment]
Please use the Amass Docker Compose. All the tools are available in the compose environment

**Comment by mariuskimmina** [comment]
Just so I get this right, large parts of `amass` are now proprietary and now longer available as open-source software?

**Comment by caffix** [comment]
Docker != proprietary. You're using a version of the project that's over a year old. Soon, there will no longer be an amass tool, since it's now a system of systems. It's easiest to setup this system in your environment using Docker Compose. All the components are still being built from open-source software.

**Comment by mariuskimmina** [comment]
> Docker != proprietary

I know, but I can't find the source code for the track or viz commands anymore, hence why I was asking what happened to the oam-tools repo. Pointing me to the docker-compose does not answer the question where the source code for these things went. 

If they are still out there and you could point me towards them instead, then I apologize for the misunderstanding.

**Comment by caffix** [comment]
It's in the `develop` branch of the `amass` repo:
https://github.com/owasp-amass/amass/tree/develop/cmd

You can use the `oam_tools` from the Docker Compose though

**Comment by mariuskimmina** [comment]
Interesting, my apology then and thank you for taking the time to answer
