### ISSUE TITLE
It's running for too long with amass -config command.

### ISSUE THREAD

**Issue by Phoenix1112** [owasp-amass/amass#916]
hello. thanks for this project. After running ```amass -active -config config.ini -d example.com -o out.txt``` it works for at least 10 minutes and sometimes exceeds 20 minutes. most of the time, I have to terminate the amass program with the kill command in linux. it seems as if this period has been extended especially with the latest version of amass. is there a command where i can make this scan shorter?

**Comment by rvw** [comment]
I don't know whether this is related, but on my M1 Mac running Amass 3.23.1 (freshly built from source) it totally hangs when I do `amass enum -d domain.tld` or `amass enum -active -d domain.tld`. It does not give any output (waited 5-10 min) and it refuses to terminate when hitting Control-C. Also my internet connection becomes totally unresponsive, in Activity Monitor, I see lots of packets being sent/received, but there is no internet available on my machine.

If I do `amass enum -passive -d domain.tld` it just works. So maybe it has something to do with the `-active` flag?

**Comment by TerickJojo** [comment]
It took a large amount of time to finsh the work with `-active` flag.
`time amass enum -config config.ini -active -ip -o amasssub.txt -d shopee.com`
<img width="256" alt="image" src="https://user-images.githubusercontent.com/24235319/232366293-6e2e9491-f657-4d43-90e6-876afbcd329a.png">
