### ISSUE TITLE
amass made me depressed, as any command does NOTHING AT ALL on Kali Linux.

### ISSUE THREAD

**Issue by rick1day** [owasp-amass/amass#931]
amass installed and -v / -h commands only works good, the rest of commands doesn't work at all.
I spent hours and hours wasting my time trying to fix without any result until i got deeply depressed and thinking about kms
could you ensure the god d@mn stability of the tool before publishing it and make people suffer more in their miserable lives, trying to make this tool works without suffering every time they install vm, release a new version with a fix and ensure the stability or change the tool name to PIMASS (pain in my 🄰ss).

Kali Linux information:

Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2023.2
Codename:       kali-rolling

amass version:
v3.23.3

Go version:
go version go1.20.6 linux/amd64

**Comment by caffix** [comment]
I'm not sure what the problem has been with how Amass isn't being built for Kali Linux. Amass v3.23.3 works quite well, and you can rebuild the tool using the process shown on the repo readme file: 

`Download OWASP Amass by running go install -v github.com/owasp-amass/amass/v3/...@master
At this point, the binary should be in $GOPATH/bin or $HOME/go/bin`

I'm sorry you had to experience this with our tool. You can also use our Docker image if you'd like to be on the safe side.
