### ISSUE TITLE
Result output problem

### ISSUE THREAD

**Issue by glockie029** [owasp-amass/amass#947]
I use this command amass enum -active -brute -o test.txt -df target.txt on ubuntu 20.04, and the output is not a single domain name but all the information about the running process of the program, I want to know how to get only the subdomain name information and save it

![image](https://github.com/owasp-amass/amass/assets/89974691/1e90c0d6-15e1-410b-ae13-b6857e2db2e4)

**Comment by glockie029** [comment]
This is what happens when the result file is saved, which makes it hard for me to sift through

**Comment by glockie029** [comment]
I found that when I used v3.23.3 I could output a list of individual domain names directly using the enum module. This is the command./amass enum --active -d xxx.xxx -o 1.txt, but after the latest version uses -o, the content of the result file is only to save the information in the process of running the program to the result file

**Comment by caffix** [comment]
The subdomains output can still be extracted using `amass db -names -d example.com` and soon will be implemented in the `oam_subs` tool. The `amass` proper tool is for collection purposes and no longer to generate output for specific use cases.

Please bring usage questions to our Discord server: https://discord.gg/HNePVyX3cp

**Comment by m4ra7h0n** [comment]
> The subdomains output can still be extracted using `amass db -names -d example.com` and soon will be implemented in the `oam_subs` tool. The `amass` proper tool is for collection purposes and no longer to generate output for specific use cases.
> 
> Please bring usage questions to our Discord server: https://discord.gg/HNePVyX3cp

But where is the amss db command now ?
