### ISSUE TITLE
Subcommands missing

### ISSUE THREAD

**Issue by soufianetahiri** [owasp-amass/amass#954]
Hello,
Looks like some subcommands are missing (viz, track,...), did I miss something ?
 
Installed via go install on latest version of Ubuntu. 
The Dockerized version misses these subcommands too.
Thank in advance  for your help!
![image](https://github.com/owasp-amass/amass/assets/17729335/556cda41-385e-46ff-8272-ee50065fde63)

**Comment by soufianetahiri** [comment]
Ok figured it out: amass viz and amass track are now separate tools: oam_*.
![image](https://github.com/owasp-amass/amass/assets/17729335/aeb9deaf-a316-45e4-aeaa-ceedf1db4d4c)

**Comment by krysopath** [comment]
even more subcommands are missing, yet oam-tools is 404

What shenanigans are going on?
