### ISSUE TITLE
flags not working

### ISSUE THREAD

**Issue by ejluciano** [owasp-amass/amass#957]
my old command used to be 

`amass enum -v -src -ip -brute -d domainhere.com`

Now when I installed it in a new machine it says 

`flag provided but not defined: -src` or `flag provided but not defined: -ip`

When I remove both flags and use `amass enum -v -brute -d google.com`
it shows `the system was unable to build the pool of untrusted resolvers`

How can I make the command `amass enum -v -src -ip -brute -d domainhere.com` work again?

**Comment by teslatheg0d** [comment]
` flag provided but not defined: -src ` 

`-src` is not working. 

Is there any other flag to print the source?

**Comment by bbolmin** [comment]
same issue

**Comment by Croco-byte** [comment]
Same issue. The '-src' flag was really useful, especially for integration with other tools. It seems like this feature was removed in latest releases, but was pertinent for various use cases.
Would it be possible to bring it back ?

**Comment by amiremami** [comment]
Same here, -src is not working

**Comment by caffix** [comment]
Amass major version 4.0 discontinued support of the `-src` flag

**Comment by sai-beep** [comment]
amass -josn flag is NOT WORKING 
flag provided but not defined: -json
FUCK amass
