### ISSUE TITLE
DataSources issue with default kali linux amass

### ISSUE THREAD

**Issue by UltraEgo5** [owasp-amass/amass#961]
Hi,

I am using the updated amass version 4.1.0 with kali linux. I am not able to use APIs integration feature.

I have created a datasources.yaml file in the folder /home/.config/amass/ directory as given in the gitbhub example folder but no luck with API integration. Can anyone help fix this

**Comment by rynmrtn** [comment]
@UltraEgo5 can you provide more information regarding what command you are running as well as what output you see in `amass.log`?

**Comment by UltraEgo5** [comment]
Thanks for responding

I am using the command amass enum -list to check whether the API integration is successful but there is no * against the SHODAN. I tried with the SHODAN API key. Please find below datasouces.yaml and amass.log file.

Please suggest.

Datasources.yaml:

datasources:
  - name: 360PassiveDNS
    ttl: 3600
    creds:
      account: 
        apikey: null
  - name: ASNLookup
    creds:
      account: 
        apikey: null
  - name: Ahrefs
    ttl: 4320
    creds:
      account: 
        apikey: null
  - name: AlienVault
    creds:
      account: 
        apikey: null
  - name: BeVigil
    creds:
      account: 
        apikey: null
  - name: BigDataCloud
    creds:
      account: 
        apikey: null
  - name: BinaryEdge
    ttl: 10080
    creds:
      account: 
        apikey: null
  - name: BufferOver
    creds:
      account: 
        apikey: null
  - name: BuiltWith
    ttl: 10080
    creds:
      account: 
        apikey: null
  - name: C99
    ttl: 4320
    creds:
      account1: 
        apikey: null
      account2: 
        apikey: null
  - name: Censys
    ttl: 10080
    creds:
      account: 
        apikey: null
        secret: null
  - name: Chaos
    ttl: 4320
    creds:
      account: 
        apikey: null
  - name: CIRCL
    creds:
      account: 
        username: null
        password: null
  - name: CertCentral
    creds:
      account: 
        username: null
        apikey: null
  - name: DNSDB
    ttl: 4320
    creds:
      account: 
        apikey: null
  - name: DNSlytics
    creds:
      account: 
        apikey: null
  - name: DNSRepo
    creds:
      account: 
        apikey: null
  - name: Deepinfo
    creds:
      account: 
        apikey: null
  - name: Detectify
    creds:
      account: 
        apikey: null
  - name: FacebookCT
    ttl: 4320
    creds:
      app1: 
        apikey: null
        secret: null
      app2: 
        apikey: null
        secret: null
  - name: FOFA
    ttl: 10080
    creds:
      account: 
        username: null
        apikey: null
  - name: FullHunt
    creds:
      account: 
        apikey: null
  - name: GitHub
    ttl: 4320
    creds:
      accountname: 
        apikey: null
  - name: GitLab
    ttl: 4320
    creds:
      accountname: 
        apikey: null
  - name: HackerTarget
    ttl: 1440
    creds:
      account: 
        apikey: null
  - name: Hunter
    creds:
      account: 
        apikey: null
  - name: IntelX
    creds:
      account: 
        apikey: null
  - name: IPdata
    creds:
      account: 
        apikey: null
  - name: IPinfo
    creds:
      account: 
        apikey: null
  - name: LeakIX
    creds:
      account: 
        apikey: null
  - name: Netlas
    creds:
      account: 
        apikey: null
  - name: ONYPHE
    ttl: 4320
    creds:
      account: 
        apikey: null
  - name: Pastebin
    ttl: 10080
    creds:
      account: 
        apikey: null
  - name: PassiveTotal
    ttl: 10080
    creds:
      account: 
        username: null
        apikey: null
  - name: PentestTools
    ttl: 10080
    creds:
      account: 
        apikey: null
  - name: PublicWWW
    ttl: 10080
    creds:
      account: 
        apikey: null
  - name: Quake
    ttl: 4320
    creds:
      account: 
        apikey: null
  - name: SOCRadar
    creds:
      account: 
        apikey: null
  - name: SecurityTrails
    ttl: 1440
    creds:
      account: 
        apikey: null
  - name: Shodan
    ttl: 10080
    creds:
      account: 
        apikey: flmcK8VKBupNBPPekVpC4Qozx9TWeOCH
  - name: Spamhaus
    ttl: 1440
    creds:
      account: 
        username: null
        password: null
  - name: ThreatBook
    creds:
      account1: 
        apikey: null
  - name: URLScan
    creds:
      account: 
        apikey: null
  - name: VirusTotal
    ttl: 10080
    creds:
      account: 
        apikey: null
  - name: WhoisXMLAPI
    creds:
      account: 
        apikey: null
  - name: Yandex
    ttl: 1440
    creds:
      account: 
        username: null
        apikey: null
  - name: ZETAlytics
    ttl: 1440
    creds:
      account: 
        apikey: null
  - name: ZoomEye
    ttl: 1440
    creds:
      account: 
        username: null
        password: null                     

# this is the global options that will be considered. For example, minimum_ttl would be a global option used to compare
# the minimum_ttl to the other datasources ttl.
global_options: 
  minimum_ttl: 1440

Amass.log:

22:59:11.621909 BufferOver: check callback failed for the configuration
22:59:11.622024 ASNLookup: check callback failed for the configuration
22:59:11.622137 ONYPHE: check callback failed for the configuration
22:59:11.622206 C99: check callback failed for the configuration
22:59:11.622268 Pastebin: check callback failed for the configuration
22:59:11.622294 BeVigil: check callback failed for the configuration
22:59:11.622330 PublicWWW: check callback failed for the configuration
22:59:11.622368 BinaryEdge: check callback failed for the configuration
22:59:11.622399 Quake: check callback failed for the configuration
22:59:11.622522 Ahrefs: check callback failed for the configuration
22:59:11.621918 360PassiveDNS: check callback failed for the configuration
22:59:11.622641 SOCRadar: check callback failed for the configuration
22:59:11.622667 DNSDB: check callback failed for the configuration
22:59:11.622028 ZoomEye: check callback failed for the configuration
22:59:11.622114 Netlas: check callback failed for the configuration
22:59:11.622756 SecurityTrails: check callback failed for the configuration
22:59:11.622058 BuiltWith: check callback failed for the configuration
22:59:11.622813 DNSlytics: check callback failed for the configuration
22:59:11.622853 VirusTotal: check callback failed for the configuration
22:59:11.622881 Detectify: check callback failed for the configuration
22:59:11.622905 Spamhaus: check callback failed for the configuration
22:59:11.622928 ThreatBook: check callback failed for the configuration
22:59:11.622952 Yandex: check callback failed for the configuration
22:59:11.622377 Chaos: check callback failed for the configuration
22:59:11.622990 ZETAlytics: check callback failed for the configuration
22:59:11.622338 CertCentral: check callback failed for the configuration
22:59:11.622318 Censys: check callback failed for the configuration
22:59:11.623058 Hunter: check callback failed for the configuration
22:59:11.622243 PassiveTotal: check callback failed for the configuration
22:59:11.623151 IPdata: check callback failed for the configuration
22:59:11.623163 IPinfo: check callback failed for the configuration
22:59:11.622961 FOFA: check callback failed for the configuration
22:59:11.622923 WhoisXMLAPI: check callback failed for the configuration
22:59:11.622860 Deepinfo: check callback failed for the configuration
22:59:11.622296 CIRCL: check callback failed for the configuration
22:59:11.622319 PentestTools: check callback failed for the configuration
22:59:11.622347 BigDataCloud: check callback failed for the configuration
22:59:11.622750 DNSRepo: check callback failed for the configuration
22:59:11.622862 Shodan: check callback failed for the configuration
22:59:11.622982 FacebookCT: check callback failed for the configuration
22:59:11.623003 FullHunt: check callback failed for the configuration
22:59:11.623048 GitHub: check callback failed for the configuration
22:59:11.623071 GitLab: check callback failed for the configuration
22:59:11.623141 IntelX: check callback failed for the configuration

**Comment by rynmrtn** [comment]
thanks @UltraEgo5. For starters, please edit your comment to remove/redact the shodan api key

**Comment by UltraEgo5** [comment]
I manipulated it before posting :) Anyways I have removed the key now

**Comment by UltraEgo5** [comment]
I am not sure whether i have configured amass properly to use the datasources. Can anyone help me with the settings I need to do, to use the datasources. Not sure if I need to use the config.yaml as well and set it using the "amass enum -list ---config config.yaml"

Please suggest

**Comment by UltraEgo5** [comment]
Hi, The issue seems resolved for me. I have copied the config.yaml and datasources.yaml file in .config/amass/ folder in my kali linux. On running the command "amass enum -config config.yaml -list" , I am getting the * against the API i have added. So the issue is solved for me.

Below are my config.yaml file content for reference, where i have removed other things for now:

options:  
  datasources: "./datasources.yaml" # the file path that will point to the data source configuration
