### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by theadventuresofhacker** [owasp-amass/amass#991]
-config flag no longer accepts *.ini configurations files in v4.2.0.

Example:

 amass enum -v -config config.ini -o amass-out.txt

Failed to load the configuration file: error mapping configuration settings to internal values: yaml: unmarshal errors:
  line 5: cannot unmarshal !!str `share =...` into config.Config

Is there any way to get config.ini to work instead of creating a new yaml config file?

Thanks

**Comment by The-Inceptions** [comment]
Amass 4.0+ only handles the new YAML configuration format.

Check out the [oam_i2y](https://github.com/owasp-amass/config#installing-oam_i2y-) tool. This will convert your INI file into the compliant YAML format.
